### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by Vipale** [datahaven-net/epp-python-client#29]
I get the following error when I try to use the client.

Windows 10 | python 3.11.3
and
Windows 11 | python 3.10.10

```
from epp import epp_client
conn = epp_client.EPPConnection(
	host='myhost',
	port=7001,
	user='myuser',
	password='mypw',
	verbose=True,
)
conn.open()
print(conn.domain_check(domain_name='domain-may-not-exist.com'))
conn.close()
```

```
Traceback (most recent call last):
  File "C:\xxx\xxx\epp-python-client\test.py", line 9, in <module>
    conn.open()
  File "C:\Users\xxx\AppData\Roaming\Python\Python311\site-packages\epp\epp_client.py", line 102, in open
    raise exc
  File "C:\Users\xxx\AppData\Roaming\Python\Python311\site-packages\epp\epp_client.py", line 99, in open
    self.ssl = ssl.wrap_socket(self.socket)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\ssl.py", line 1446, in wrap_socket
    return context.wrap_socket(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\ssl.py", line 1075, in _create
    self.do_handshake()
  File "C:\Program Files\Python311\Lib\ssl.py", line 1346, in do_handshake
    self._sslobj.do_handshake()
FileNotFoundError: [Errno 2] No such file or directory
```

Any idea how to fix this?

**Comment by vesellov** [comment]
Hello @Vipale 

Not sure, but it looks to me this bug report is very similar to your issue : https://bugs.python.org/issue35324

Could be that OpenSSL is somehow not configured properly on your Windows laptop?

I only tested and deployed this lib on Linux...

Another idea is to try to use Python 3.8

**Comment by Vipale** [comment]
Hello @vesellov,

thanks for your input. This bug report helped me to figure it out.

The error occured because my IP wasn't allowed to connect. So the connection attempt was rejected.
The error message is just very misleading.

**Comment by vesellov** [comment]
Nice. Good luck, @Vipale .
